name: Unit test
runs:
  using: "composite"
  steps:
    - name: Unit test
      run: flutter test --coverage --coverage-path=./coverage/lcov-unit_tests.info
      shell: bash
    - name: Upload unit test coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov-unit_tests.info
        flags: unit_tests
        fail_ci_if_error: true
        verbose: true