name: 'Install dependencies'
runs:
  using: 'composite'
  steps:
# FIXME cacheされていない気がする
    - id: cache
      name: 'Cache'
      uses: actions/cache@v3
      with:
        path: |
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
          **/.dart_tool/flutter_gen/pubspec.yaml
          ${{ env.PUB_CACHE }}
          **/.packages
        key: dependencies-${{ hashFiles('pubspec.lock') }}
    - name: 'Get Packages'
      if: steps.cache.outputs.cache-hit != 'true'
      run: flutter packages pub get
      shell: bash
