name: 'Integration test(Android)'
inputs:
  api-level:
    required: true
  tag:
    default: 'default'
  arch:
    default: 'x86_64'
  codecov-token:
    required: true
runs:
  using: 'composite'
  steps:
    - run: flutter doctor -v
      shell: bash
    - uses: malinskiy/action-android/emulator-run-cmd@release/0.1.3
      with:
        cmd: flutter test integration_test/app_test.dart
        api: ${{ inputs.api-level }}
        tag: ${{ inputs.tag }}
        abi: ${{ inputs.arch }}
