// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'models.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:MemTable.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// MemTable TABLE
class TableMemTable extends SqfEntityTableBase {
  TableMemTable() {
    // declare properties of EntityTable
    tableName = 'memTable';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('name', DbType.text, isNotNull: false),
      SqfEntityFieldBase('remarks', DbType.text, isNotNull: false),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableMemTable();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class MemDbModel extends SqfEntityModelProvider {
  MemDbModel() {
    databaseName = memDbModel.databaseName;
    password = memDbModel.password;
    dbVersion = memDbModel.dbVersion;
    databaseTables = [
      TableMemTable.getInstance,
    ];

    bundledDatabasePath = memDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region MemTable
class MemTable {
  MemTable({this.id, this.name, this.remarks, this.isDeleted}) {
    _setDefaultValues();
  }
  MemTable.withFields(this.name, this.remarks, this.isDeleted) {
    _setDefaultValues();
  }
  MemTable.withId(this.id, this.name, this.remarks, this.isDeleted) {
    _setDefaultValues();
  }
  MemTable.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['name'] != null) {
      name = o['name'] as String;
    }
    if (o['remarks'] != null) {
      remarks = o['remarks'] as String;
    }
    isDeleted = o['isDeleted'] != null
        ? o['isDeleted'] == 1 || o['isDeleted'] == true
        : null;
  }
  // FIELDS (MemTable)
  int id;
  String name;
  String remarks;
  bool isDeleted;

  BoolResult saveResult;
  // end FIELDS (MemTable)

  static const bool _softDeleteActivated = true;
  MemTableManager __mnMemTable;

  MemTableManager get _mnMemTable {
    return __mnMemTable = __mnMemTable ?? MemTableManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (name != null) {
      map['name'] = name;
    }

    if (remarks != null) {
      map['remarks'] = remarks;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (name != null) {
      map['name'] = name;
    }

    if (remarks != null) {
      map['remarks'] = remarks;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method returns Json String [MemTable]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [MemTable]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [name, remarks, isDeleted];
  }

  List<dynamic> toArgsWithIds() {
    return [id, name, remarks, isDeleted];
  }

  static Future<List<MemTable>> fromWebUrl(Uri url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR MemTable.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri url, {Map<String,
      String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<MemTable>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <MemTable>[];
    try {
      objList = list
          .map((memtable) => MemTable.fromMap(memtable as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR MemTable.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<MemTable>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<MemTable> objList = <MemTable>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = MemTable.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns MemTable by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns MemTable if exist, otherwise returns null
  Future<MemTable> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    MemTable obj;
    final data = await _mnMemTable.getById([id]);
    if (data.length != 0) {
      obj = MemTable.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (MemTable) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnMemTable.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnMemTable.update(this);
    }

    return id;
  }

  /// saveAs MemTable. Returns a new Primary Key value of MemTable

  /// <returns>Returns a new Primary Key value of MemTable
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<MemTable> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<MemTable> memtables) async {
    // final results = _mnMemTable.saveAll('INSERT OR REPLACE INTO memTable (id,name, remarks,isDeleted)  VALUES (?,?,?,?)',memtables);
    // return results; removed in sqfentity_gen 1.3.0+6
    await MemDbModel().batchStart();
    for (final obj in memtables) {
      await obj.save();
    }
    //    return MemDbModel().batchCommit();
    final result = await MemDbModel().batchCommit();
    for (int i = 0; i < memtables.length; i++) {
      if (memtables[i].id == null) {
        memtables[i].id = result[i] as int;
      }
    }

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnMemTable.rawInsert(
              'INSERT OR REPLACE INTO memTable (id,name, remarks,isDeleted)  VALUES (?,?,?,?)',
              [id, name, remarks, isDeleted]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'MemTable id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'MemTable id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'MemTable Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<MemTable>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<MemTable> memtables) async {
    final results = await _mnMemTable.rawInsertAll(
        'INSERT OR REPLACE INTO memTable (id,name, remarks,isDeleted)  VALUES (?,?,?,?)',
        memtables);
    return results;
  }

  /// Deletes MemTable

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete MemTable invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnMemTable
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnMemTable.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover MemTable>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover MemTable invoked (id=$id)');
    {
      return _mnMemTable.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  MemTableFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return MemTableFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  MemTableFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return MemTableFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion memtable

// region MemTableField
class MemTableField extends SearchCriteria {
  MemTableField(this.memtableFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  MemTableFilterBuilder memtableFB;

  MemTableField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  MemTableFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    memtableFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, memtableFB.parameters, param, SqlSyntax.EQuals,
            memtableFB._addedBlocks)
        : setCriteria(pValue, memtableFB.parameters, param, SqlSyntax.NotEQuals,
            memtableFB._addedBlocks);
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }

  MemTableFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    memtableFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, memtableFB.parameters, param,
            SqlSyntax.EQualsOrNull, memtableFB._addedBlocks)
        : setCriteria(pValue, memtableFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, memtableFB._addedBlocks);
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }

  MemTableFilterBuilder isNull() {
    memtableFB._addedBlocks = setCriteria(
        0,
        memtableFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        memtableFB._addedBlocks);
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }

  MemTableFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      memtableFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          memtableFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          memtableFB._addedBlocks);
      _waitingNot = '';
      memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
          memtableFB._addedBlocks.retVal;
    }
    return memtableFB;
  }

  MemTableFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      memtableFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          memtableFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          memtableFB._addedBlocks);
      _waitingNot = '';
      memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
          memtableFB._addedBlocks.retVal;
      memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
          memtableFB._addedBlocks.retVal;
    }
    return memtableFB;
  }

  MemTableFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      memtableFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          memtableFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          memtableFB._addedBlocks);
      _waitingNot = '';
      memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
          memtableFB._addedBlocks.retVal;
    }
    return memtableFB;
  }

  MemTableFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      memtableFB._addedBlocks = setCriteria(
          pFirst,
          memtableFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          memtableFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        memtableFB._addedBlocks = setCriteria(pFirst, memtableFB.parameters,
            param, SqlSyntax.LessThan, memtableFB._addedBlocks);
      } else {
        memtableFB._addedBlocks = setCriteria(pFirst, memtableFB.parameters,
            param, SqlSyntax.GreaterThanOrEquals, memtableFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        memtableFB._addedBlocks = setCriteria(pLast, memtableFB.parameters,
            param, SqlSyntax.GreaterThan, memtableFB._addedBlocks);
      } else {
        memtableFB._addedBlocks = setCriteria(pLast, memtableFB.parameters,
            param, SqlSyntax.LessThanOrEquals, memtableFB._addedBlocks);
      }
    }
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }

  MemTableFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    memtableFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, memtableFB.parameters, param,
            SqlSyntax.GreaterThan, memtableFB._addedBlocks)
        : setCriteria(pValue, memtableFB.parameters, param,
            SqlSyntax.LessThanOrEquals, memtableFB._addedBlocks);
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }

  MemTableFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    memtableFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, memtableFB.parameters, param, SqlSyntax.LessThan,
            memtableFB._addedBlocks)
        : setCriteria(pValue, memtableFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, memtableFB._addedBlocks);
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }

  MemTableFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    memtableFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, memtableFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, memtableFB._addedBlocks)
        : setCriteria(pValue, memtableFB.parameters, param, SqlSyntax.LessThan,
            memtableFB._addedBlocks);
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }

  MemTableFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    memtableFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, memtableFB.parameters, param,
            SqlSyntax.LessThanOrEquals, memtableFB._addedBlocks)
        : setCriteria(pValue, memtableFB.parameters, param,
            SqlSyntax.GreaterThan, memtableFB._addedBlocks);
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }

  MemTableFilterBuilder inValues(dynamic pValue) {
    memtableFB._addedBlocks = setCriteria(
        pValue,
        memtableFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        memtableFB._addedBlocks);
    _waitingNot = '';
    memtableFB._addedBlocks.needEndBlock[memtableFB._blockIndex] =
        memtableFB._addedBlocks.retVal;
    return memtableFB;
  }
}
// endregion MemTableField

// region MemTableFilterBuilder
class MemTableFilterBuilder extends SearchCriteria {
  MemTableFilterBuilder(MemTable obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  MemTable _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  MemTableFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  MemTableFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  MemTableFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  MemTableFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  MemTableFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  MemTableFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  MemTableFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  MemTableFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  MemTableFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  MemTableFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  MemTableFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  MemTableField setField(MemTableField field, String colName, DbType dbtype) {
    return MemTableField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  MemTableField _id;
  MemTableField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  MemTableField _name;
  MemTableField get name {
    return _name = setField(_name, 'name', DbType.text);
  }

  MemTableField _remarks;
  MemTableField get remarks {
    return _remarks = setField(_remarks, 'remarks', DbType.text);
  }

  MemTableField _isDeleted;
  MemTableField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value = param.value == null
                  ? null
                  : param.value == true
                      ? 1
                      : 0;
              param.value2 = param.value2 == null
                  ? null
                  : param.value2 == true
                      ? 1
                      : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (MemTable._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<MemTable> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (MemTable._softDeleteActivated && !hardDelete) {
      r = await _obj._mnMemTable.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnMemTable.delete(qparams);
    }
    return r;
  }

  /// Recover List<MemTable> bulk by query
  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover MemTable bulk invoked');
    return _obj._mnMemTable.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from memTable ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnMemTable.updateBatch(qparams, values);
  }

  /// This method always returns MemTable Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<MemTable>
  Future<MemTable> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnMemTable.toList(qparams);
    final data = await objFuture;
    MemTable obj;
    if (data.isNotEmpty) {
      obj = MemTable.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [MemTable]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) memtableCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final memtablesFuture = await _obj._mnMemTable.toList(qparams);
    final int count = memtablesFuture[0]['CNT'] as int;
    if (memtableCount != null) {
      memtableCount(count);
    }
    return count;
  }

  /// This method returns List<MemTable> [MemTable]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<MemTable>
  Future<List<MemTable>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<MemTable> memtablesData = await MemTable.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return memtablesData;
  }

  /// This method returns Json String [MemTable]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [MemTable]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [MemTable]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnMemTable.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [MemTable]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM memTable WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnMemTable.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [MemTable]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnMemTable.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await MemTable.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnMemTable.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion MemTableFilterBuilder

// region MemTableFields
class MemTableFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField _fRemarks;
  static TableField get remarks {
    return _fRemarks =
        _fRemarks ?? SqlSyntax.setField(_fRemarks, 'remarks', DbType.text);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion MemTableFields

//region MemTableManager
class MemTableManager extends SqfEntityProvider {
  MemTableManager()
      : super(MemDbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'memTable';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion MemTableManager
class MemDbModelSequenceManager extends SqfEntityProvider {
  MemDbModelSequenceManager() : super(MemDbModel());
}
// END OF ENTITIES
