// Mocks generated by Mockito 5.0.7 from annotations
// in mem/test/mem_detail_test.dart.
// Do not manually edit this file.

import 'package:mem/database/mem_dao.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [MemDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemDao extends _i1.Mock implements _i2.MemDao {
  MockMemDao() {
    _i1.throwOnMissingStub(this);
  }
}
