name: 'Install Flutter with cache'
inputs:
  channel:
    default: 'stable'
  version:
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Define env key'
      run: echo "key=${{ inputs.channel }}-${{ inputs.version }}-${{ runner.arch }}" >> $GITHUB_ENV
      shell: bash
# TODO 何をしているのかよく分からないが遅すぎる。代替方法がないか検討する
    - id: install-flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.version }}
        channel: ${{ inputs.channel }}
        cache: true
        cache-key: flutter-${{ env.key }}
