name: mem
description: To manage.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # for Database
  sqfentity: ^1.4.0+3
  sqfentity_gen: ^1.2.3
  http: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # for Database
  build_runner: ^1.6.5
  build_verify: ^1.1.0

flutter:
  uses-material-design: true

