name: mem
description: Manage any.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # for Database
  sqflite:
  path:
  sqflite_common_ffi:
  path_provider:
  idb_shim:

  # for View state management
  flutter_riverpod:

  # for basic operations
  collection:

  # for Logger
  logger:

  intl:

dev_dependencies:
  integration_test:
      sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # for Test mock
  mockito:
  build_runner:

flutter:
  uses-material-design: true

  generate: true
