name: mem
description: Manage any.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # for Database
  sqflite:
  path:
  sqflite_common_ffi:
  path_provider:
  idb_shim:

  # for View state management
  flutter_riverpod:

  # for basic operations
  collection:

  # for Logger
  logger:

  intl:

dev_dependencies:
  integration_test:
      sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # for Test mock
  mockito:
  build_runner:

  # for Icon
  flutter_launcher_icons:

flutter:
  uses-material-design: true

  generate: true

flutter_icons:
  image_path: "assets/icon/launcher_icon.png"
  android: true
  adaptive_icon_background: "#03A9F4"
  adaptive_icon_foreground: "assets/icon/launcher_icon.png"
  min_sdk_android: 21
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/web_hi_res_512.png"
    icon_size: 256
  web:
    generate: true
    image_path: "assets/icon/web_hi_res_512.png"
    background_color: "#03A9F4"
    theme_color: "#000000"