name: mem
description: Manage any.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # for View
  intl:
  flutter_picker: ^2.1.0

  ## for SettingsPage
  settings_ui: ^2.0.2

  ## for View state management
  flutter_riverpod:

  # for Notification
  flutter_local_notifications:
  timezone:

  # for Persistence
  ## for Database
  sqflite:
  path:
  sqflite_common_ffi:
  path_provider:
  idb_shim:

  ## for Logger
  logger:

  ## for Preferences
  shared_preferences: ^2.2.2

  # for basic operations
  collection:

  # for Home widgets
  home_widget: ^0.2.0+1
  workmanager: ^0.5.1
  fl_chart: ^0.63.0
  flutter_sticky_header: ^0.6.5
  android_alarm_manager_plus: ^3.0.4

dev_dependencies:
  # for Test mock
  test:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito:
  build_runner:

  flutter_lints: ^2.0.0

  # for Icon
  flutter_launcher_icons:

flutter:
  uses-material-design: true

  generate: true

flutter_icons:
  image_path: "assets/icon/launcher_icon.png"
  android: true
  adaptive_icon_background: "#03A9F4"
  adaptive_icon_foreground: "assets/icon/launcher_icon.png"
  min_sdk_android: 21
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/web_hi_res_512.png"
    icon_size: 256
  web:
    generate: true
    image_path: "assets/icon/web_hi_res_512.png"
    background_color: "#03A9F4"
    theme_color: "#000000"