# https://taskfile.dev

version: '3'

includes:
  flutter: ./tools/task/flutter.taskfile.yml
  f: ./tools/task/flutter.taskfile.yml
  emulator: ./tools/task/emulator.taskfile.yml
  e: ./tools/task/emulator.taskfile.yml
  git: ./tools/task/git.taskfile.yml

tasks:
  default:
    desc: "利用可能なタスク一覧を表示します"
    cmds:
      - task --list
    silent: true

  gen:
    desc: "コード生成を実行します。"
    cmds:
      - task: flutter:gen
    silent: false

  init:
    desc: "初期化を実行します。"
    cmds:
      - task: git:setup-git-hooks

  pre-push-checks:
    desc: "Run all checks required before pushing (from tools/flutter.Taskfile.yml)"
    cmds:
      - task: flutter:analyze
      - task: flutter:test
