# https://taskfile.dev

version: '3'

includes:
  flutter: ./tools/task/flutter.taskfile.yml
  f: ./tools/task/flutter.taskfile.yml
  emulator: ./tools/task/emulator.taskfile.yml
  e: ./tools/task/emulator.taskfile.yml
  git: ./tools/task/git.taskfile.yml
  dependency: ./tools/task/dependency.taskfile.yml

tasks:
  default:
    cmds:
      - task --list
    silent: true

  dep:status:
    vars:
      p: '{{.p | default ""}}'
    cmds:
      - task: dependency:status
        vars:
          PACKAGE: '{{.p}}'
    silent: false
  
  dep:upgrade:
    vars:
      p: '{{.p}}'
    cmds:
      - task: dependency:upgrade
        vars:
          PACKAGE: '{{.p}}'
    silent: false


  gen:
    cmds:
      - task: flutter:gen
      - task: flutter:gen:l10n
    silent: false

  watch:
    cmds:
      - task: flutter:gen
        vars:
          MODE: watch
    silent: false

  init:
    cmds:
      - task: git:setup-git-hooks

  lint:
    cmds:
      - task: flutter:analyze:app
      - task: flutter:analyze:generated
      - task: flutter:analyze:test

  run:
    cmds:
      - task: flutter:run
  
  test:
    cmds:
      - task: flutter:test
      - task: flutter:test:integration

  pre-commit-checks:
    cmds:
      - task: lint

  pre-push-checks:
    cmds:
      - task: flutter:test
