# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  flutter-analyze:
    desc: "Run Flutter static analysis"
    cmds:
      - flutter analyze
    silent: false

  flutter-test:
    desc: "Run Flutter tests"
    cmds:
      - flutter test
    silent: false

  pre-push-checks:
    desc: "Run all checks required before pushing"
    cmds:
      - task: flutter-analyze
      - task: flutter-test

  setup-hooks:
    desc: "Set up Git hooks by symlinking them from scripts/git-hooks to .git/hooks"
    cmds:
      - |
        #!/bin/sh
        HOOK_DIR=$(git rev-parse --git-dir)/hooks
        SCRIPT_DIR=$(git rev-parse --show-toplevel)/scripts/git-hooks
        echo "Hook dir: $HOOK_DIR"
        echo "Script dir: $SCRIPT_DIR"
        mkdir -p "$HOOK_DIR"
        echo "Setting up pre-push hook..."
        if [ -f "$SCRIPT_DIR/pre-push.sh" ]; then
          ln -sf "../../scripts/git-hooks/pre-push.sh" "$HOOK_DIR/pre-push"
          chmod +x "$HOOK_DIR/pre-push"
          chmod +x "$SCRIPT_DIR/pre-push.sh"
          echo "Pre-push hook set up."
        else
          echo "Error: scripts/git-hooks/pre-push.sh not found."
          exit 1
        fi
    silent: false
    # Windows ユーザー向けに、シンボリックリンクが使えない場合の代替コピーコマンドも考慮するとより親切ですが、
    # まずは Unix ライクな環境を対象とします。
    #  - For Windows, you might need to copy instead of symlink, or ensure symlinks are enabled.
    #    Example (requires admin or developer mode on Windows):
    #    - cmd: mklink .git\hooks\pre-push scripts\git-hooks\pre-push.sh
    #    Or copy:
    #    - cmd: copy scripts\git-hooks\pre-push.sh .git\hooks\pre-push.sh /Y
