# https://taskfile.dev

version: '3'

includes:
  flutter: ./tools/task/flutter.taskfile.yml
  f: ./tools/task/flutter.taskfile.yml
  emulator: ./tools/task/emulator.taskfile.yml
  e: ./tools/task/emulator.taskfile.yml
  git: ./tools/task/git.taskfile.yml

tasks:
  default:
    desc: "利用可能なタスク一覧を表示します"
    cmds:
      - task --list
    silent: true

  gen:
    desc: "コード生成を実行します。"
    cmds:
      - task: flutter:gen
    silent: false

  watch:
    desc: "コード生成を実行のため、ソースコードを監視します。"
    cmds:
      - task: flutter:gen
        vars:
          MODE: watch
    silent: false

  init:
    desc: "初期化を実行します。"
    cmds:
      - task: git:setup-git-hooks

  dep:
    desc: "依存関係を更新します。"
    cmds:
      - task: flutter:dep

  dep:check:
    desc: "依存関係を更新します。"
    cmds:
      - task: flutter:dep:check
        silent: true

  dep:update:
    desc: "依存関係を更新します。"
    cmds:
      - task: flutter:dep:update

  run:
    desc: "アプリを実行します。"
    cmds:
      - task: flutter:run

  pre-commit-checks:
    desc: "Run all checks required before committing (from tools/flutter.Taskfile.yml)"
    cmds:
      - task: flutter:analyze

  pre-push-checks:
    desc: "Run all checks required before pushing (from tools/flutter.Taskfile.yml)"
    cmds:
      - task: flutter:test
