name: "Install flutter"
description: "Flutterを実行可能状態にし、doctorを使って状態を確認する"

inputs:
  flutter-channel:
    description: "Flutter channel"
    required: true
  flutter-version:
    description: "Flutter version"

runs:
  using: "composite"

  steps:
    - name: "Install Flutter"
      uses: subosito/flutter-action@main
      with:
        channel: ${{ inputs.flutter-channel }}
        flutter-version: ${{ inputs.flutter-version }}
        cache: true

    - run: flutter doctor -v
      shell: bash

    - run: dart pub global activate rps
      shell: bash
