name: 'Install Flutter'
inputs:
  version:
    type: string
    required: true
  channel:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Install Flutter'
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.version }}
        channel: ${{ inputs.channel }}
        cache: true
