name: "Set up Java and Gradle"

inputs:
  java-distribution:
    required: true
  java-version:
    required: true

runs:
  using: composite

  steps:
    - name: "Set up Java"
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
#        FIXME これ必要か？
#         TODO 動作を確認する
#        cache: gradle

    - name: "Set up Gradle"
      uses: gradle/gradle-build-action@v2