name: Set up AVD
inputs:
  method:
    type: choice
    description: Which to run
    required: true
    options:
      - malinskiy
      - reactivecircus
  java-distribution:
    required: true
  java-version:
    required: true
  flutter-channel:
    required: true
  android-api-level:
    required: true
  android-target:
    required: true
  android-arch:
    required: true

runs:
  using: composite
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: gradle
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ inputs.flutter-channel }}
        cache: true
    - name: AVD cache
      uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.android-api-level }}-${{ inputs.android-target }}-${{ inputs.android-arch }}
    - name: "Create AVD and generate snapshot for chaching"
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android-api-level }}
        target: ${{ inputs.android-target }}
        arch: ${{ inputs.android-arch }}
        profile: Nexus 6
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."