name: "Run Android Medium test"
description: "Run Android Medium test"

inputs:
  android-emulator-runner:
    description: "android-emulator-runner"
    required: true
  script:
    required: true
    description: "script"
  android-api-level:
    required: true
    description: "android-api-level"
  android-target:
    description: "android-target"
    required: true
  android-arch:
    description: "android-arch"
    required: true
  experimental:
    description: "experimental"
    default: "false"

runs:
  using: "composite"

  steps:
    - if: inputs.android-emulator-runner == 'reactivecircus-linux'
      id: run-android-medium_test-via-reactivecircus-linux
      name: "Run Android Medium Test via reactivecircus linux"
      uses: ./.github/actions/run-android-medium_test-via-reactivecircus-linux
      with:
        script: ${{ inputs.script }}
        android-api-level: ${{ inputs.android-api-level }}
        android-target: ${{ inputs.android-target }}
        android-arch: ${{ inputs.android-arch }}
      #          android-device-profile: Pixel 5
