name: "Run Android Medium test"

inputs:
  android-emulator-runner:
  android-api-level:
    required: true
  android-target:
    required: true
  android-arch:
    required: true

outputs:
  status: ${{ steps.set-result.outputs.status }}

runs:
  using: composite

  steps:
    - id: run-android-medium_test-via-malinskiy
      name: "Run Android Medium Test via malinskiy"
      if: inputs.android-emulator-runner == 'malinskiy'
      uses: ./.github/actions/run-android-medium_test-via-malinskiy
      with:
        android-api-level: 29
        android-target: default
        android-arch: x86_64
      continue-on-error: true

    - id: run-android-medium_test-via-reactivecircus
      name: "Run Android Medium Test via reactivecircus"
      if: inputs.android-emulator-runner == 'reactivecircus'
      uses: ./.github/actions/run-android-medium_test-via-reactivecircus
      with:
        android-api-level: 29
        android-target: default
        android-arch: x86_64
  #          android-device-profile: Pixel 5
      continue-on-error: true

    - id: set-result-malinskiy
      if: matrix.android-emulator-runner == 'malinskiy'
      name: "Set Result (malinskiy)"
      run: echo "STATUS=${{ steps.run-android-medium_test-via-malinskiy.outcome }}" >> $GITHUB_ENV
    - id: set-result-reactivecircus
      if: matrix.android-emulator-runner == 'reactivecircus'
      name: "Set Result (reactivecircus)"
      run: echo "STATUS=${{ steps.run-android-medium_test-via-reactivecircus.outcome }}" >> $GITHUB_Env

    - id: set-result
      name: "Set Result"
      run: echo "status=STATUS" >> $GITHUB_OUTPUT
