name: "Run Android Medium test"
description: "Run Android Medium test"

inputs:
  android-emulator-runner:
    description: "android-emulator-runner"
    required: true
  script:
    required: true
    description: "script"
  android-api-level:
    required: true
    description: "android-api-level"
  android-target:
    description: "android-target"
    required: true
  android-arch:
    description: "android-arch"
    required: true
  experimental:
    description: "experimental"
    default: "false"

outputs:
  status:
    value: ${{ steps.set-result.outputs.status }}
    description: "status"

runs:
  using: "composite"

  steps:
    - if: inputs.android-emulator-runner == 'malinskiy'
      id: run-android-medium_test-via-malinskiy
      name: "Run Android Medium Test via malinskiy"
      uses: ./.github/actions/run-android-medium_test-via-malinskiy
      with:
        script: ${{ inputs.script }}
        android-api-level: ${{ inputs.android-api-level }}
        android-target: ${{ inputs.android-target }}
        android-arch: ${{ inputs.android-arch }}
      continue-on-error: ${{ inputs.experimental }}

    - if: inputs.android-emulator-runner == 'reactivecircus'
      id: run-android-medium_test-via-reactivecircus
      name: "Run Android Medium Test via reactivecircus"
      uses: ./.github/actions/run-android-medium_test-via-reactivecircus
      with:
        script: ${{ inputs.script }}
        android-api-level: ${{ inputs.android-api-level }}
        android-target: ${{ inputs.android-target }}
        android-arch: ${{ inputs.android-arch }}
      #          android-device-profile: Pixel 5
      continue-on-error: ${{ inputs.experimental }}

    - if: inputs.android-emulator-runner == 'native'
      id: run-android-medium_test-via-native
      name: "Run Android Medium Test via native"
      uses: ./.github/actions/run-android-medium_test-via-native
      with:
        script: ${{ inputs.script }}
        android-api-level: ${{ inputs.android-api-level }}
        android-target: ${{ inputs.android-target }}
        android-arch: ${{ inputs.android-arch }}
      continue-on-error: ${{ inputs.experimental == 'true' }}

    - if: matrix.android-emulator-runner == 'malinskiy'
      name: "Set Result (malinskiy)"
      run: echo "STATUS=${{ steps.run-android-medium_test-via-malinskiy.outcome }}" >> $GITHUB_ENV
      shell: bash
    - if: matrix.android-emulator-runner == 'reactivecircus'
      name: "Set Result (reactivecircus)"
      run: echo "STATUS=${{ steps.run-android-medium_test-via-reactivecircus.outcome }}" >> $GITHUB_ENV
      shell: bash
    - if: matrix.android-emulator-runner == 'native'
      name: "Set Result (native)"
      run: echo "STATUS=${{ steps.run-android-medium_test-via-native.outcome }}" >> $GITHUB_ENV
      shell: bash

    - id: set-result
      name: "Set Result"
      run: echo "status=$STATUS" >> $GITHUB_OUTPUT
      shell: bash
