name: "Run Android Medium test via reactivecircus"
description: "Run Android Medium test via reactivecircus."

inputs:
  script:
    description: "script"
    required: true
  android-api-level:
    description: "android-api-level"
    required: true
  android-target:
    description: "android-target"
    required: true
  android-arch:
    description: "android-arch"
    required: true
# TODO 有効なProfileを見つける
#   画面サイズなどのバラエティを増やす際に検討する
#  android-device-profile:
#    required: true

runs:
  using: "composite"

  steps:
    - name: "AVD cache"
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.android-api-level }}-${{ inputs.android-target }}-${{ inputs.android-arch }}-reactivecircus

    - name: "Create Android virtual device"
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android-api-level }}
        target: ${{ inputs.android-target }}
        arch: ${{ inputs.android-arch }}
        #        profile: ${{ inputs.android-device-profile }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: echo "Generated AVD snapshot for caching."

    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android-api-level }}
        target: ${{ inputs.android-target }}
        arch: ${{ inputs.android-arch }}
        #        profile: ${{ inputs.android-device-profile }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ${{ inputs.script }}
