name: "Run Android Medium test via reactivecircus"
description: "Run Android Medium test via reactivecircus."

inputs:
  script:
    description: "script"
    required: true
  android-api-level:
    description: "android-api-level"
    required: true
  android-target:
    description: "android-target"
    required: true
  android-arch:
    description: "android-arch"
    required: true
# TODO 有効なProfileを見つける
#   画面サイズなどのバラエティを増やす際に検討する
#  android-device-profile:
#    required: true

runs:
  using: "composite"

  steps:
    - name: "AVD cache"
      uses: actions/cache@v4
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.android-api-level }}-${{ inputs.android-target }}-${{ inputs.android-arch }}-reactivecircus

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    - name: Clean up disk space
      run: |
        # 不要なファイルを削除してディスク容量を確保
        sudo apt-get clean
        sudo rm -rf /var/lib/apt/lists/*
        sudo rm -rf /tmp/*
        # 古いDockerイメージを削除（もしあれば）
        docker system prune -af 2>/dev/null || true
      shell: bash

    - name: Move AVD storage to /tmp
      run: |
        # /tmp にディレクトリを作る
        mkdir -p /tmp/android-avd

        # 既存の ~/.android/avd を削除 or バックアップ
        rm -rf ~/.android/avd

        # シンボリックリンクを作る
        ln -s /tmp/android-avd ~/.android/avd

        # 権限を確認（念のため）
        chmod -R 777 /tmp/android-avd
      shell: bash

    - name: "Create Android virtual device"
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android-api-level }}
        target: ${{ inputs.android-target }}
        arch: ${{ inputs.android-arch }}
        #        profile: ${{ inputs.android-device-profile }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot -partition-size 256 -memory 1024 -cores 2
        disable-animations: false
        disk-size: 256
        script: echo "Generated AVD snapshot for caching."

    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android-api-level }}
        target: ${{ inputs.android-target }}
        arch: ${{ inputs.android-arch }}
        #        profile: ${{ inputs.android-device-profile }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot -partition-size 256 -memory 1024 -cores 2
        disable-animations: true
        disk-size: 256
        script: ${{ inputs.script }}
