name: Set up AVD
inputs:
  android-api-level:
    required: true
  android-target:
    required: true
  android-arch:
    required: true

runs:
  using: composite
  steps:
    - name: "AVD cache"
      uses: actions/cache@v3
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.android-api-level }}-${{ inputs.android-target }}-${{ inputs.android-arch }}-${{ inputs.method }}

    - name: "Create Android virtual device"
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android-api-level }}
        target: ${{ inputs.android-target }}
        arch: ${{ inputs.android-arch }}
        profile: Pixel 7 Pro
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        script: flutter doctor -v

    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: default
        arch: x86_64
        profile: Nexus 6
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: >
          flutter test integration_test/app_test.dart
          --coverage
          --dart-define=CICD=true
          --device-id "emulator-5554"
          --file-reporter json:reports/test_report.log
#          bash ./scripts/integration_test.sh "emulator-5554"
#          script: flutter test integration_test/app_test.dart --machine  -d android --coverage --dart-define=CICD=true | tee >(grep "^{" | grep "}$" > temp_report.log)
