name: "Analyze code"

on:
  workflow_call:
    inputs:
      flutter-channel:
        type: string
        required: true
      flutter-version:
        type: string

jobs:
  analyze-code:
    name: "Analyze code"
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4

      - name: "Flutter doctor"
        uses: ./.github/actions/flutter-doctor
        with:
          flutter-channel: ${{ inputs.flutter-channel }}
          flutter-version: ${{ inputs.flutter-version }}

      - name: "Install Dependencies"
        uses: ./.github/actions/install-dependencies

      - name: "Analyze Application code"
        run: flutter analyze lib

      - name: "Analyze Riverpod lints"
        run: dart run custom_lint

      - name: "Build Mocks"
        uses: ./.github/actions/build-mocks

      - name: "Analyze Test code"
        run: flutter analyze test integration_test
