name: "Continuous Delivery"

on:
  #  debugのために必要
  workflow_dispatch:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

env:
  flutter-channel: stable
  #  flutter-version: 3.19.6

jobs:
  upload_for_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Java and Gradle"
        uses: ./.github/actions/set_up-java-and-gradle
        with:
          java-distribution: zulu
          java-version: 17

      - name: "Flutter doctor"
        uses: ./.github/actions/flutter-doctor
        with:
          flutter-channel: ${{ env.flutter-channel }}
          flutter-version: ${{ env.flutter-version }}

      - name: "Create jks"
        run: echo -n ${{ secrets.ANDROID_KEY_JKS }} | base64 -d > android/mem.jks

      - name: "Create key.properties"
        run: |
          echo 'storeFile=../mem.jks' > android/key.properties
          echo 'storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}' >> android/key.properties
          echo 'keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}' >> android/key.properties
          echo 'keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}' >> android/key.properties

      - name: "Build Android AppBundle"
        run: flutter build appbundle --build-number ${GITHUB_RUN_NUMBER}

      - name: "Create Service account key"
        run: echo -n ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }} | base64 -d > service-account-key.json

      - name: "Upload to Google play"
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          serviceAccountJson: service-account-key.json
          packageName: zin.playground.mem
          track: internal
          status: draft
