name: "Continuous Delivery"

on:
  # debugのために必要
  workflow_dispatch:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

env:
  flutter-channel: stable
#  flutter-version: 3.27.4

jobs:
  upload_for_android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Build Android AppBundle"
        uses: ./.github/actions/build-android-app_bundle
        with:
          flutter-channel: ${{ env.flutter-channel }}
          flutter-version: ${{ env.flutter-version }}
          ANDROID_KEY_JKS: ${{ secrets.ANDROID_KEY_JKS }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}

      - name: "Create Service account key"
        run: echo -n ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }} | base64 -d > service-account-key.json

      - name: "Upload to Google play"
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          serviceAccountJson: service-account-key.json
          packageName: zin.playground.mem
          track: internal
          status: draft
