name: "Continuous Integration"

on:
  push:

env:
  flutter-channel: stable

jobs:
  analyze-code:
    name: "Analyze code"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
          cache: true

      - name: "Install Dependencies"
        uses: ./.github/actions/install-dependencies

      - name: "Analyze Application code"
        run: flutter analyze lib

      - name: "Generate Mocks"
        uses: ./.github/actions/build-mocks
      - name: "Analyze Test code"
        run: flutter analyze test integration_test

  small_test:
    name: "Small test"
    runs-on: ubuntu-latest
    # TODO medium_test-androidと同様にReusable Workflowにしてもいいかもしれない
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
          cache: true

      - name: "Generate Mocks"
        uses: ./.github/actions/build-mocks

      - name: "Run Flutter test"
        run: >
          flutter test
          --coverage
          --file-reporter json:reports/test_report.log

      - name: "Report"
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: "Report (Small test)"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: false
          fail-on-empty: false
      - name: "Upload coverage"
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: small_test

  medium_test-android:
    name: "Medium test(Android)"
    uses: ./.github/workflows/medium_test-android.yml
    with:
      # TODO ci配下のすべての環境を揃えたい。envを使うための回避策を考える
#      flutter-channel: "${{ env.flutter-channel }}"
      flutter-channel: stable
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test-windows:
    name: "Medium test(Windows)"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
          cache: true

      - name: "Generate Localization code"
        uses: ./.github/actions/generate-localization_code

      - name: "Run Windows Medium Test"
        run: >
          flutter test integration_test/app_test.dart
          --dart-define=CICD=true
          --coverage
          --device-id windows
          --file-reporter json:reports/test_report.log

      - name: "Report"
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: "Report (Medium test (Windows))"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: false
          fail-on-empty: false
      - name: "Upload coverage"
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: medium_test-windows
