# Continuous Integration
name: "CI"

on:
  push:

env:
  flutter-channel: stable
  # FIXME https://github.com/zin-/mem/issues/339
  flutter-version: 3.19.6

jobs:
  set_up-env:
    name: "Set up Environment variables"
    timeout-minutes: 3
    outputs:
      flutter-channel: ${{ steps.env-variables.outputs.flutter-channel }}
      flutter-version: ${{ steps.env-variables.outputs.flutter-version }}
    runs-on: ubuntu-latest
    steps:
      - id: env-variables
        name: "Set up Environment variables"
        # description: "reusing-workflowsの呼び出しではwithにenvを指定できないためoutputsに変換する"
        run: |
          echo "flutter-channel=${{ env.flutter-channel }}" >> $GITHUB_OUTPUT
          echo "flutter-version=${{ env.flutter-version }}" >> $GITHUB_OUTPUT

  analyze-code:
    needs: set_up-env
    uses: ./.github/workflows/analyze-code.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}
      flutter-version: ${{ needs.set_up-env.outputs.flutter-version }}

  small_test:
    needs: set_up-env
    uses: ./.github/workflows/small_test.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}
      flutter-version: ${{ needs.set_up-env.outputs.flutter-version }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test:
    strategy:
      matrix:
        target: [
          framework,
          scenarios/app_test.dart,
          scenarios/settings_scenario.dart
        ]
        include:
          - timeout-minutes-android: 20
          - target: scenarios/settings_scenario.dart
            timeout-minutes-android: 40
      fail-fast: true

    needs: set_up-env
    uses: ./.github/workflows/medium_test.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}
      flutter-version: ${{ needs.set_up-env.outputs.flutter-version }}
      test-script: flutter test integration_test/${{ matrix.target }} --dart-define=CICD=true --file-reporter json:reports/test_report.log --coverage
      target: ${{ matrix.target }}
      timeout-minutes-android: ${{ matrix.timeout-minutes-android }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
