# Continuous Integration
name: "CI"

on:
  push:

env:
  flutter-channel: stable
  flutter-version: 3.27.4

jobs:
  set_up-env:
    name: "Set up Environment variables"
    timeout-minutes: 3
    outputs:
      flutter-channel: ${{ steps.env-variables.outputs.flutter-channel }}
      flutter-version: ${{ steps.env-variables.outputs.flutter-version }}
    runs-on: ubuntu-latest
    steps:
      - id: env-variables
        name: "Set up Environment variables"
        # description: "reusing-workflowsの呼び出しではwithにenvを指定できないためoutputsに変換する"
        run: |
          echo "flutter-channel=${{ env.flutter-channel }}" >> $GITHUB_OUTPUT
          echo "flutter-version=${{ env.flutter-version }}" >> $GITHUB_OUTPUT

  analyze-code:
    needs: set_up-env
    uses: ./.github/workflows/analyze-code.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}
      flutter-version: ${{ needs.set_up-env.outputs.flutter-version }}

  small_test:
    needs: set_up-env
    uses: ./.github/workflows/small_test.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}
      flutter-version: ${{ needs.set_up-env.outputs.flutter-version }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test:
    strategy:
      matrix:
        target: [
          scenarios/settings/settings_test.dart,
          scenarios/app_test.dart,
          framework
        ]
        include:
          - timeout-minutes-android: 30
            timeout-minutes-windows: 15
          - target: scenarios/settings/settings_test.dart
            timeout-minutes-android: 50
      fail-fast: true

    needs: set_up-env
    uses: ./.github/workflows/medium_test.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}
      flutter-version: ${{ needs.set_up-env.outputs.flutter-version }}
      test-script: flutter test integration_test/${{ matrix.target }} --dart-define=CICD=true --file-reporter json:reports/test_report.log --coverage
      target: ${{ matrix.target }}
      timeout-minutes-android: ${{ matrix.timeout-minutes-android }}
      timeout-minutes-windows: ${{ matrix.timeout-minutes-windows }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build-android-app_bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build Android AppBundle"
        uses: ./.github/actions/build-android-app_bundle
        with:
          flutter-channel: ${{ env.flutter-channel }}
          flutter-version: ${{ env.flutter-version }}
          ANDROID_KEY_JKS: ${{ secrets.ANDROID_KEY_JKS }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
