# Continuous Integration
name: "CI"

on:
  push:

env:
  flutter-channel: stable

jobs:
  set_up-env:
    name: "Set up Environment variables"
    timeout-minutes: 3
    outputs:
      flutter-channel: ${{ steps.env-variables.outputs.flutter-channel }}
    runs-on: ubuntu-latest
    steps:
      - id: env-variables
        name: "Set up Environment variables"
        # description: "reusing-workflowsの呼び出しではwithにenvを指定できないためoutputsに変換する"
        run: |
          echo "flutter-channel=${{ env.flutter-channel }}" >> $GITHUB_OUTPUT

  analyze-code:
    needs: set_up-env
    uses: ./.github/workflows/analyze-code.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}

  small_test:
    needs: set_up-env
    uses: ./.github/workflows/small_test.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test:
    strategy:
      matrix:
        target: [
          framework,
          scenarios/memo,
          scenarios/habit,
          scenarios/memo_scenario.dart,
          scenarios/todo_scenario.dart,
          scenarios/task_scenario.dart,
          scenarios/notification_scenario.dart,
          scenarios/settings_scenario.dart,
          scenarios/edge_scenario.dart
        ]
      fail-fast: true

    needs: set_up-env
    uses: ./.github/workflows/medium_test.yml
    with:
      flutter-channel: ${{ needs.set_up-env.outputs.flutter-channel }}
      test-script: >
        flutter test integration_test/${{ matrix.target }}
        --dart-define=CICD=true
        --file-reporter json:reports/test_report.log
        --coverage
      target: ${{ matrix.target }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
