name: "[EX]Continuous Integration"

on:
  push:

env:
  flutter-channel: stable

jobs:
  analyze-code:
#  TODO skipを解除する
    if: false # 計算コスト削減のため一時的にskipする
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
#        flutter-channel: [ stable, beta, master]

    name: "Analyze code on ${{ matrix.os }}"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
          cache: true

      - name: "Analyze Application code"
        run: flutter analyze lib

      - name: "Generate Mocks"
        uses: ./.github/actions/build-mocks
      - name: "Analyze Test code"
        run: flutter analyze test integration_test

  small_test:
#  TODO skipを解除する
    if: false # 計算コスト削減のため一時的にskipする
    name: "Small test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
          cache: true

      - name: "Generate Mocks"
        uses: ./.github/actions/build-mocks

      - name: "Run Flutter test"
        run: >
          flutter test
          --coverage
          --file-reporter json:reports/test_report.log

      - name: "Report"
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: "Small test report"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: false
          fail-on-empty: false
      - name: "Upload coverage"
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: small_test

  medium_test-android:
    name: "Medium test(Android)"
    uses: ./.github/workflows/medium_test-android.yml
    with:
      flutter-channel: ${{ env.flutter-channel }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test-windows:
#  TODO skipを解除する
    if: false # 計算コスト削減のため一時的にskipする
    name: "Medium test(Windows)"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
          cache: true

      - name: "Generate Localization code"
        uses: ./.github/actions/generate-localization_code

      - name: "Run Windows Medium Test"
        run: >
          flutter test integration_test/app_test.dart
          --dart-define=CICD=true
          --coverage
          --device-id windows
          --file-reporter json:reports/test_report.log

      - name: "Report"
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: "Medium test report(Windows)"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: false
          fail-on-empty: false
      - name: "Upload coverage"
        if: always()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: ex-medium_test-windows
