name: "[EX]Continuous Integration"

on:
  push:

env:
  flutter-channel: stable

jobs:
  analyze-code:
    name: "Analyze code on ${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
#        flutter-channel: [ stable, beta, master]
#        analyze-target: [ application, test ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
#          channel: ${{ matrix.flutter-channel }}
          cache: true

      - name: "Analyze Application code"
#        if: ${{ matrix.analyze-target == 'application' }}
        run: flutter analyze lib

      - name: "Generate Mocks"
#        if: ${{ matrix.analyze-target == 'test' }}
        uses: ./.github/actions/build-mocks
      - name: "Analyze Test code"
#        if: ${{ matrix.analyze-target == 'test' }}
        run: flutter analyze test integration_test

  small_test:
    name: 'Small test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: 'Install Flutter'
        uses: ./.github/actions/install-flutter
        with:
          version: ${{ env.flutter-version }}
          channel: ${{ env.flutter-channel }}
      - name: 'Install dependencies'
        uses: ./.github/actions/install-dependencies
      - name: 'Build Mocks'
        uses: ./.github/actions/build-mocks
      - name: 'Generate Localization code'
        uses: ./.github/actions/generate-localization_code
      - name: 'Flutter Doctor'
        run: flutter doctor -v
      - id: 'test_execution'
        continue-on-error: true
        run: flutter test --coverage
      - name: 'Upload coverage'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: small_test
      - name: 'Error handling'
        if: ${{ steps.test_execution.outcome == 'failure' }}
        run: exit 1

  medium_test-android:
    name: "Medium test(Android)"

    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
# TODO 複数のAndroid Emulator Runnerを使う
#   - malinskiy/action-android
#   - reactivecircus/android-emulator-runner
#   パフォーマンスチェックのため
#   Github actionsの実行時間制限とかが出始めたらやめる
        android-emulator-runner: [ malinskiy, reactivecircus ]

# TODO 画面サイズ
# TODO OSバージョン
# TODO Java distribution
# TODO Java version

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter-channel }}
          cache: true

      - name: 'Generate Localization code'
        uses: ./.github/actions/generate-localization_code

      - name: Run Android Integration Test
        uses: ./.github/actions/set_up-avd
        with:
          method: ${{ matrix.android-emulator-runner }}
          java-distribution: zulu
          java-version: 11
          android-api-level: 29
          android-target: default
          android-arch: x86_64

      - name: "Upload coverage"
        if: success() || failure()
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: medium_test-android-ex-${{ matrix.android-emulator-runner }}

      - name: Report
        if: success() || failure()
        uses: dorny/test-reporter@v1
        with:
#          name: '${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}'
          name: 'Medium test(Android)'
          path: 'temp_report.log'
          reporter: 'flutter-json'
          fail-on-error: true
