name: Lint
on: [push]
jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Flutter
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: flutter pub get
        run: flutter pub get
      - name: Analyze
        run: dart analyze . --fatal-infos