name: Lint
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
#      - name: Install Flutter
#        run: ./.github/workflows/scripts/install-flutter.sh
      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true
      - name: flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - run: flutter packages get
      - name: Build
        run: ./.github/workflows/scripts/build.sh
      - name: Analyze
        run: flutter analyze
