name: "[EX] Medium test(android)"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # Flutterのバージョンを指定
          cache: true

      - name: "Install dependencies"
        run: flutter pub get

      - name: 'Generate Localization code'
        uses: ./.github/actions/generate-localization_code

      - name: "Build Mocks"
        uses: ./.github/actions/build-mocks

      - name: "Build APK"
        run: flutter build apk

      - name: Setup Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          script: echo "Generated AVD snapshot for caching."

      - name: Run Flutter Tests
        run: flutter test integration_test/app_test.dart -d ${{ matrix.platform }} --coverage --dart-define=CICD=true
