name: "[EX] Medium test(android)"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable  # Flutterのバージョンを指定
          cache: true

      - name: "Install dependencies"
        run: flutter pub get

      - name: 'Generate Localization code'
        uses: ./.github/actions/generate-localization_code

      - name: 'Build Mocks'
        uses: ./.github/actions/build-mocks

      - name: Build APK
        run: flutter build apk

      - name: Setup Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30  # 使用するAndroid APIレベルを指定
          target: default  # 使用するエミュレータの名前を指定
          emulator-options: -accel on  # エミュレータのオプションを指定

      - name: Start Emulator
        run: |
          emulator -avd default -no-audio -no-window &
          sleep 30  # エミュレータが起動するのを待つために適切な時間を設定

      - name: Wait for Emulator to Start
        run: adb wait-for-device

      - name: Run Flutter Tests
        run: flutter test
