name: "Medium test (Android)"

on:
  workflow_call:
    inputs:
      flutter-channel:
        type: string
        required: true
      flutter-version:
        type: string
      test-script:
        type: string
        required: true
      target:
        type: string
        required: true
      timeout-minutes:
        type: number
        required: true

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  medium_test-android:
    strategy:
      matrix:
        # 複数のAndroid Emulator Runnerを使う
        #   パフォーマンスチェックのため
        #   Github actionsの実行時間制限とかが出始めたらやめる
        android-emulator-runner: [ reactivecircus-linux ]
        include:
          # - os: macos-latest
          # FIXME macos-14とreactivecircusでエラーになるため、バージョンを指定している
          # https://github.com/ReactiveCircus/android-emulator-runner/issues/350
          - os: ubuntu-latest
            java-version: 17
            experimental: false
            android-api-level: 33
            android-arch: x86_64
          - android-emulator-runner: native
            experimental: true
      fail-fast: false

    name: "Medium test (Android) (${{ matrix.android-emulator-runner }}) (${{ inputs.target }})"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: ${{ inputs.timeout-minutes }}

    # TODO 画面サイズ
    # TODO OSバージョン
    # TODO Java distribution
    # TODO Java version

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Java and Gradle"
        uses: ./.github/actions/set_up-java-and-gradle
        with:
          java-distribution: zulu
          java-version: ${{ matrix.java-version }}

      - name: "Flutter doctor"
        uses: ./.github/actions/install-flutter
        with:
          flutter-channel: ${{ inputs.flutter-channel }}
          flutter-version: ${{ inputs.flutter-version }}

      - name: "Install Dependencies"
        uses: ./.github/actions/install-dependencies

      - name: "Run build_runner"
        run: dart run build_runner build --delete-conflicting-outputs

      - name: "Build APK"
        run: flutter build apk --debug

      - id: run-android-medium_test
        name: "Run Android Medium test"
        uses: ./.github/actions/run-android-medium_test
        with:
          android-emulator-runner: ${{ matrix.android-emulator-runner }}
          script: ${{ inputs.test-script }}
          android-api-level: ${{ matrix.android-api-level }}
          android-target: default
          android-arch: ${{ matrix.android-arch }} # FIXME これandroidのarchじゃなくて動かす側のcpu archだ
          experimental: ${{ matrix.experimental }}
        continue-on-error: ${{ matrix.experimental == true }}

      - if: always()
        name: "Report"
        uses: dorny/test-reporter@v1
        with:
          name: "Report (Medium test (Android) (${{ inputs.target }})) (${{ matrix.android-emulator-runner }})"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: true
          fail-on-empty: true
        continue-on-error: ${{ matrix.experimental == true }}
      - if: always()
        name: "Upload coverage"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: medium_test-android-${{ inputs.target }}-${{ matrix.android-emulator-runner }}
        continue-on-error: ${{ matrix.experimental == true }}
