name: "Medium test (Android)"

on:
  workflow_call:
    inputs:
      flutter-channel:
        type: string
        required: true
      flutter-version:
        type: string
      test-script:
        type: string
        required: true
      target:
        type: string
        required: true
      timeout-minutes:
        type: number
        required: true

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  medium_test-android:
    name: "Medium test (Android) (${{ inputs.target }})"
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}

    # TODO 画面サイズ
    # TODO OSバージョン
    # TODO Java distribution
    # TODO Java version

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Java and Gradle"
        uses: ./.github/actions/set_up-java-and-gradle
        with:
          java-distribution: zulu
          java-version: 17

      - name: "Flutter doctor"
        uses: ./.github/actions/install-flutter
        with:
          flutter-channel: ${{ inputs.flutter-channel }}
          flutter-version: ${{ inputs.flutter-version }}

      - name: "Install Dependencies"
        uses: ./.github/actions/install-dependencies

      - name: "Run build_runner"
        run: dart run build_runner build --delete-conflicting-outputs

      - name: "Build APK"
        run: flutter build apk --debug

      - id: run-android-medium_test
        name: "Run Android Medium test"
        uses: ./.github/actions/run-android-medium_test-via-reactivecircus-linux
        with:
          script: ${{ inputs.script }}
          android-api-level: 33
          android-target: default
          android-arch: x86_64
          #          android-device-profile: Pixel 5

      - if: always()
        name: "Report"
        uses: dorny/test-reporter@v1
        with:
          name: "Report (Medium test (Android) (${{ inputs.target }}))"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: true
          fail-on-empty: true
      - if: always()
        name: "Upload coverage"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: medium_test-android-${{ inputs.target }}
