name: "[EX] Medium test(android)"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29-default-x86_64
      - name: Create AVD and generate snapshot for chaching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          emulator-boot-timeout: 1800 # キャッシュが効いていない初回起動のみ必要かもしれない
          disable-linux-hw-accel: false
          script: echo "Generated AVD snapshot for caching."

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # Flutterのバージョンを指定
          cache: true

      - name: "Install dependencies"
        run: flutter pub get

      - name: 'Generate Localization code'
        uses: ./.github/actions/generate-localization_code

      - name: "Build Mocks"
        uses: ./.github/actions/build-mocks

      - name: "Build APK"
        run: flutter build apk

      - name: Run Flutter Tests
        run: flutter test integration_test/app_test.dart -d ${{ matrix.platform }} --coverage --dart-define=CICD=true
