name: "Medium test"

on:
  workflow_call:
    inputs:
      flutter-channel:
        type: string
        required: true
      flutter-version:
        type: string
        required: true
      test-script:
        type: string
        required: true
      target:
        type: string
        required: true
      timeout-minutes-android:
        type: number
        required: true
      timeout-minutes-windows:
        type: number
        required: true

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  medium_test-android:
    uses: ./.github/workflows/medium_test-android.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
      flutter-version: ${{ inputs.flutter-version }}
      test-script: >
        ${{ inputs.test-script }} --device-id "emulator-5554"
      target: ${{ inputs.target }}
      timeout-minutes: ${{ inputs.timeout-minutes-android }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test-windows:
    uses: ./.github/workflows/medium_test-windows.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
      flutter-version: ${{ inputs.flutter-version }}
      test-script: ${{ inputs.test-script }} --device-id windows
      target: ${{ inputs.target }}
      timeout-minutes: ${{ inputs.timeout-minutes-windows }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
