name: "Medium test"

on:
  workflow_call:
    inputs:
      flutter-channel:
        required: true
        type: string
      test-script:
        required: true
        type: string
      target:
        required: true
        type: string
      timeout-minutes-android:
        required: true
        type: number

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  medium_test-android:
    uses: ./.github/workflows/medium_test-android.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
      test-script: >
        ${{ inputs.test-script }} --device-id "emulator-5554"
      target: ${{ inputs.target }}
      timeout-minutes: ${{ inputs.timeout-minutes-android }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test-windows:
    uses: ./.github/workflows/medium_test-windows.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
      test-script: ${{ inputs.test-script }} --device-id windows
      target: ${{ inputs.target }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
