name: "Medium test (Windows)"

on:
  workflow_call:
    inputs:
      flutter-channel:
        required: true
        type: string
      test-script:
        required: true
        type: string
      target:
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  medium_test-windows:
    name: "Medium test (Windows)(${{ inputs.target }}))"
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: "Flutter doctor"
        uses: ./.github/actions/flutter-doctor
        with:
          flutter-channel: ${{ inputs.flutter-channel }}

      - name: "Install Dependencies"
        uses: ./.github/actions/install-dependencies

      - name: "Run Windows Medium Test"
        run: ${{ inputs.test-script }}

      - if: always()
        name: "Report"
        uses: dorny/test-reporter@v1
        with:
          name: "Report (Medium test (Windows)(${{ inputs.target }}))"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: true
          fail-on-empty: true
      - if: always()
        name: "Upload coverage"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: medium_test-windows-${{ inputs.target }}
