name: "Medium test"

on:
  workflow_call:
    inputs:
      flutter-channel:
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

env:
  run-medium_test-script: >
    flutter test integration_test/app_test.dart
    --dart-define=CICD=true
    --coverage
    --file-reporter json:reports/test_report.log

jobs:
  medium_test-android:
    uses: ./.github/workflows/medium_test-android.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
      script: ${{ env.run-medium_test-script }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test-windows:
    uses: ./.github/workflows/medium_test-windows.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
      script: ${{ env.run-medium_test-script }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
