name: "[EX] Medium test(android)"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up JDK 8"
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: "Install Flutter"
        run: |
          git clone https://github.com/flutter/flutter.git ~/flutter
          export PATH=~/flutter/bin:$PATH
          flutter doctor -v
          flutter pub get

      - name: "Run Tests and Collect Coverage"
        run: flutter test --coverage --dart-define=CICD=true

      - name: 'Upload coverage'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: medium_test-android-ex