name: "Medium test"

on:
  workflow_call:
    inputs:
      flutter-channel:
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  medium_test-android:
    uses: ./.github/workflows/medium_test-android.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  medium_test-windows:
    uses: ./.github/workflows/medium_test-windows.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
      test-script: >
        flutter test integration_test/app_test.dart
        --dart-define=CICD=true
        --file-reporter json:reports/test_report.log
        --coverage
        --device-id windows
      target: all
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ex-medium_test-windows:
    strategy:
      matrix:
        target: [
          framework,
          scenarios/memo,
          scenarios/habit,
          scenarios/memo_scenario.dart
        ]
      fail-fast: true
      max-parallel: 5

    uses: ./.github/workflows/medium_test-windows.yml
    with:
      flutter-channel: ${{ inputs.flutter-channel }}
      test-script: >
        flutter test integration_test/${{ matrix.target }}
        --dart-define=CICD=true
        --file-reporter json:reports/test_report.log
        --coverage
        --device-id windows
      target: ${{ matrix.target }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
