name: "Medium test (Android)"

on:
  workflow_call:
    inputs:
      flutter-channel:
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  medium_test-android:
    name: "Medium test (Android)"

    strategy:
      matrix:
        # 複数のAndroid Emulator Runnerを使う
        #   パフォーマンスチェックのため
        #   Github actionsの実行時間制限とかが出始めたらやめる
        android-emulator-runner: [ malinskiy, reactivecircus, native ]
        include:
          - os: macos-latest
            java-version: 11
            experimental: false
          - android-emulator-runner: malinskiy
            experimental: true
          - android-emulator-runner: native
            os: ubuntu-latest
            experimental: true
            java-version: 17
      fail-fast: false

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    # TODO 画面サイズ
    # TODO OSバージョン
    # TODO Java distribution
    # TODO Java version

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Java and Gradle"
        uses: ./.github/actions/set_up-java-and-gradle
        with:
          java-distribution: zulu
          java-version: ${{ matrix.java-version }}
      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ inputs.flutter-channel }}
          cache: true
      - name: "Flutter doctor"
        uses: ./.github/actions/flutter-doctor

      - name: "Install Dependencies"
        uses: ./.github/actions/install-dependencies

      - name: "Build APK"
        run: flutter build apk --debug

      - id: run-android-medium_test
        name: "Run Android Medium test"
        uses: ./.github/actions/run-android-medium_test
        with:
          android-emulator-runner: ${{ matrix.android-emulator-runner }}
          script: >
            flutter test integration_test/app_test.dart
            --dart-define=CICD=true
            --file-reporter json:reports/test_report.log
            --coverage
            --device-id "emulator-5554"
          android-api-level: 29
          android-target: default
          android-arch: x86_64 # FIXME これandroidのarchじゃなくて動かす側のcpu archだ
          experimental: ${{ matrix.experimental }}
        continue-on-error: ${{ matrix.experimental == 'true' }}

      - if: always()
        name: "Report"
        uses: dorny/test-reporter@v1
        with:
          name: "Report (Medium test (Android)) (${{ matrix.android-emulator-runner }})"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: true
          fail-on-empty: true
        continue-on-error: ${{ matrix.experimental == 'true' }}
      - if: always()
        name: "Upload coverage"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: medium_test-android-${{ matrix.android-emulator-runner }}
        continue-on-error: ${{ matrix.experimental == 'true' }}
