name: "Small test"

on:
  workflow_call:
    inputs:
      flutter-channel:
        type: string
        required: true
      flutter-version:
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  small_test:
    name: "Small test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: "Flutter doctor"
        uses: ./.github/actions/install-flutter
        with:
          flutter-channel: ${{ inputs.flutter-channel }}
          flutter-version: ${{ inputs.flutter-version }}

      - name: "Install Dependencies"
        uses: ./.github/actions/install-dependencies

      - name: "Run build_runner"
        run: dart run build_runner build --delete-conflicting-outputs

      - name: "Generate l10n"
        uses: ./.github/actions/generate-l10n

      - name: "Run Flutter test"
        run: >
          flutter test
          --file-reporter json:reports/test_report.log
          --coverage

      - if: always()
        name: "Report"
        uses: dorny/test-reporter@v1
        with:
          name: "Report (Small test)"
          path: "reports/test_report.log"
          reporter: "flutter-json"
          fail-on-error: true
          fail-on-empty: true
      - if: always()
        name: "Upload coverage"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: small_test