name: 'Static code analysis'
on: push
env:
  flutter-version: 3.0.3
  flutter-channel: 'stable'
jobs:
  analyze-production_code:
    name: 'Analyze Production code'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: 'Install Flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: ${{ env.flutter-channel }}
          cache: true
      - name: 'Generate Localization codes'
        run: flutter gen-l10n l10n.yaml
      - name: 'Flutter Doctor'
        run: flutter doctor -v
      - name: 'Analyze Production code'
        run: flutter analyze lib

  analyze-test_code:
    name: 'Analyze Test code'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
      - name: 'Install Flutter'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: ${{ env.flutter-channel }}
          cache: true
      - name: 'Install Dependencies'
        run: flutter packages pub get
      - name: 'Build mocks'
        run: flutter pub run build_runner build
      - name: 'Flutter Doctor'
        run: flutter doctor -v
      - name: 'Analyze Test code'
        run: flutter analyze test integration_test
