name: Test
on: [push]
jobs:
  Test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Unit test
        run: flutter test --coverage --coverage-path=~/coverage/lcov-unit_tests.info
      - name: Integration test on Windows
        run: flutter test ./integration_test/all.dart --machine -d windows --coverage --coverage-path=~/coverage/lcov-integration_tests-windows.info
      - name: Upload unit test coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov-unit_tests.info
          flags: unit_tests
          fail_ci_if_error: true
          verbose: true
      - name: Upload Windows integration test coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov-integration_tests-windows.info
          flags: windows-integration_tests
          fail_ci_if_error: true
          verbose: true
