name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: test
        run: flutter test --coverage --coverage-path=~/coverage/lcov.info
