name: Integration test on Windows
inputs:
  codecov-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Unit test
      run: flutter test ./integration_test/all.dart --machine -d windows --coverage --coverage-path=./coverage/lcov-integration_tests-on-windows.info
      shell: bash
    - name: Upload unit test coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        files: ./coverage/lcov-integration_tests-on-windows.info
        flags: integration_tests-on-windows
        fail_ci_if_error: true
        verbose: true
